export const KO_DOM_TEXT_OVERRIDES: Record<string, string> = {
  // Workflow list / screenshot-critical chrome
  "Your Agents": "내 에이전트",
  "Active Agents": "활성 에이전트",
  "Upload Agent Definition": "에이전트 정의 업로드",
  "New Folder": "새 폴더",
  "Create Agent": "에이전트 생성",
  "No active workflows found. Create your first workflow to get started.": "활성 워크플로가 없습니다. 첫 워크플로를 생성해 시작하세요.",
  "Failed to load Workflows. Please Try Again Later.": "워크플로를 불러오지 못했습니다. 잠시 후 다시 시도하세요.",
  "Authentication required. Please refresh the page.": "인증이 필요합니다. 페이지를 새로고침해 주세요.",
  "Create Workflow": "워크플로 생성",
  "Upload Workflow": "워크플로 업로드",
  "Your Workflows": "내 워크플로",
  "Active Workflows": "활성 워크플로",
  "Archived": "보관됨",
  "Uncategorized": "미분류",
  "No workflows in this folder": "이 폴더에 워크플로가 없습니다",
  "No workflows found": "워크플로가 없습니다",
  "Create your first workflow": "첫 워크플로 생성",

  // Global/common controls
  "Slack 참여": "Slack 참여",
  "Star": "스타",
  "Latest": "최신",
  "Update": "업데이트",
  "Light Mode": "라이트 모드",
  "Dark Mode": "다크 모드",
  "Sign out": "로그아웃",
  "Actions": "작업",
  "Action": "작업",
  "Cancel": "취소",
  "Save": "저장",
  "Saving...": "저장 중...",
  "Create": "생성",
  "Creating...": "생성 중...",
  "Delete": "삭제",
  "Edit": "수정",
  "Refresh": "새로고침",
  "Refreshing...": "새로고침 중...",
  "Copy": "복사",
  "Copied": "복사됨",
  "Close": "닫기",
  "Back": "뒤로",
  "Next": "다음",
  "Previous": "이전",
  "Loading...": "불러오는 중...",
  "Status": "상태",
  "Active": "활성",
  "Inactive": "비활성",
  "Draft": "초안",
  "Published": "게시됨",
  "Pending": "대기 중",
  "Completed": "완료됨",
  "Failed": "실패",
  "Error": "오류",
  "Unknown": "알 수 없음",
  "None": "없음",
  "No data available": "데이터가 없습니다",
  "Learn more": "자세히 보기",
  "Click to copy": "클릭하여 복사",
  "Toggle Sidebar": "사이드바 전환",
  "Open Next.js Dev Tools": "Next.js 개발 도구 열기",
  "Notifications alt+T": "알림 alt+T",

  // Tools
  "Tools": "도구",
  "HTTP API": "HTTP API",
  "External HTTP API": "외부 HTTP API",
  "Make HTTP requests to external APIs": "외부 API로 HTTP 요청을 보냅니다",
  "End Call": "통화 종료",
  "End the call when conditions are met": "조건이 충족되면 통화를 종료합니다",
  "End the call when either user asks to disconnect the call, or when you believe its time to end the conversation": "사용자가 통화 종료를 요청했거나 대화를 끝낼 시점이라고 판단될 때 통화를 종료합니다",
  "Transfer Call": "통화 전환",
  "Transfer the call to another phone number (Twilio only)": "통화를 다른 전화번호로 전환합니다(Twilio 전용)",
  "Transfer the caller to another phone number when requested": "요청 시 발신자를 다른 전화번호로 전환합니다",
  "Calculator": "계산기",
  "Built-in calculator for arithmetic operations": "산술 계산용 기본 계산기",
  "Calculator Configuration": "계산기 설정",
  "Built-in calculator for arithmetic operations. No additional configuration needed.": "산술 계산용 기본 계산기입니다. 추가 설정이 필요 없습니다.",
  "MCP Server": "MCP 서버",
  "Native": "네이티브",
  "Native (Coming Soon)": "네이티브(준비 중)",
  "Integration": "연동",
  "Integration (Coming Soon)": "연동(준비 중)",
  "Built-in tools like call transfer, DTMF input": "통화 전환, DTMF 입력 같은 기본 도구",
  "Third-party integrations like Google Calendar": "Google Calendar 같은 외부 서비스 연동",
  "End Call Tool": "통화 종료 도구",
  "Transfer Call Tool": "통화 전환 도구",
  "HTTP API Tool": "HTTP API 도구",
  "Calculator Tool": "계산기 도구",
  "Native Tool": "네이티브 도구",
  "Integration Tool": "연동 도구",
  "MCP Server Tool": "MCP 서버 도구",
  "Tool": "도구",
  "Tool Name": "도구 이름",
  "Description": "설명",
  "Tool name": "도구 이름",
  "Describe what this tool does...": "이 도구가 하는 일을 설명하세요...",
  "Transfer Call Configuration": "통화 전환 설정",
  "Transfer Destination": "전환 대상",
  "Pre-Transfer Message": "전환 전 메시지",
  "No Message": "메시지 없음",
  "Custom Message": "사용자 지정 메시지",
  "Pre-recorded Audio": "사전 녹음 오디오",
  "Transfer Timeout": "전환 제한 시간",
  "Use phone number instead": "전화번호 사용",
  "Use SIP endpoint instead": "SIP 엔드포인트 사용",
  "End Call Configuration": "통화 종료 설정",
  "Capture End Call Reason": "통화 종료 사유 수집",
  "Reason Description": "사유 설명",
  "Goodbye Message": "종료 인사 메시지",
  "Tool Configuration": "도구 설정",
  "Settings": "설정",
  "Authentication": "인증",
  "Parameters": "파라미터",
  "HTTP Method": "HTTP 메서드",
  "Timeout (ms)": "제한 시간(ms)",
  "Endpoint URL": "엔드포인트 URL",
  "LLM Parameters": "LLM 파라미터",
  "Preset Parameters": "사전 설정 파라미터",
  "Custom Headers": "사용자 지정 헤더",
  "Header name": "헤더 이름",
  "Header value": "헤더 값",
  "Add Header": "헤더 추가",
  "Streamable HTTP": "Streamable HTTP",
  "No recordings available": "사용 가능한 녹음이 없습니다",
  "All parameters must have a name": "모든 파라미터에는 이름이 필요합니다",
  "All preset parameters must have a name and a value": "모든 사전 설정 파라미터에는 이름과 값이 필요합니다",

  // Campaigns
  "Campaign name": "캠페인 이름",
  "Enter campaign name": "캠페인 이름 입력",
  "Select a workflow": "워크플로 선택",
  "Select a telephony configuration": "전화 설정 선택",
  "Select source type": "소스 유형 선택",
  "Filter by date range": "날짜 범위로 필터링",
  "From": "시작",
  "To": "종료",
  "Start date": "시작일",
  "End date": "종료일",
  "Download Report": "리포트 다운로드",
  "Campaign Details": "캠페인 세부 정보",
  "Campaign Settings": "캠페인 설정",
  "Max Concurrent Calls": "최대 동시 통화 수",
  "Retries Enabled": "재시도 활성화",
  "Max Retries": "최대 재시도 횟수",
  "Retry Delay": "재시도 지연",
  "Retry On": "재시도 조건",
  "Busy": "통화 중",
  "No Answer": "응답 없음",
  "Voicemail": "음성사서함",
  "CSV File": "CSV 파일",
  "Upload CSV File": "CSV 파일 업로드",
  "Upload a CSV file with contact data. Must include phone_number column. The columns can be accessed as initial_context in the workflow nodes.": "연락처 데이터가 포함된 CSV 파일을 업로드하세요. phone_number 열이 필요합니다. 각 열은 워크플로 노드에서 initial_context로 접근할 수 있습니다.",
  "Max 10MB.": "최대 10MB.",

  // Files / recordings
  "Knowledge Base Files": "지식 베이스 파일",
  "Your Documents": "내 문서",
  "Upload Document": "문서 업로드",
  "Search documents...": "문서 검색...",
  "Full Document": "전체 문서",
  "Chunked": "청크 분할됨",
  "No documents uploaded yet": "아직 업로드된 문서가 없습니다",
  "No documents match your search": "검색과 일치하는 문서가 없습니다",
  "Recordings": "녹음",
  "Upload Recording": "녹음 업로드",
  "Search by ID, transcript, or filename...": "ID, 전사 또는 파일명으로 검색...",
  "Transcribing...": "전사 중...",
  "What does this recording say?": "이 녹음에서 어떤 말을 하나요?",
  "Uploading...": "업로드 중...",
  "Auto-transcription failed": "자동 전사에 실패했습니다",
  "Microphone access denied. Please allow microphone permissions.": "마이크 접근이 거부되었습니다. 마이크 권한을 허용해 주세요.",
  "Failed to upload recordings": "녹음을 업로드하지 못했습니다",
  "Failed to delete recording": "녹음을 삭제하지 못했습니다",
  "Failed to play recording": "녹음을 재생하지 못했습니다",

  // API keys / developer
  "Developer Portal": "개발자 포털",
  "Manage your API keys to access Recova services programmatically": "Recova 서비스를 프로그래밍 방식으로 사용하기 위한 API 키를 관리하세요",
  "API Keys": "API 키",
  "Create New API Key": "새 API 키 생성",
  "No API keys found": "API 키가 없습니다",
  "Create Your First API Key": "첫 API 키 생성",
  "Key Name": "키 이름",
  "API Key Created Successfully": "API 키가 생성되었습니다",
  "Your API Key:": "내 API 키:",
  "Recova Service Keys": "Recova 서비스 키",
  "Create New Service Key": "새 서비스 키 생성",
  "Service Key Name": "서비스 키 이름",
  "Service Key Created Successfully": "서비스 키가 생성되었습니다",
  "Your Service Key:": "내 서비스 키:",
  "Important:": "중요:",
  "Sign up for Recova Cloud": "Recova Cloud에 가입",

  // Telephony
  "Telephony configurations": "전화 설정",
  "Webhook public key not configured": "Webhook 공개 키가 설정되지 않았습니다",
  "No telephony configurations yet": "아직 전화 설정이 없습니다",
  "Delete configuration?": "설정을 삭제할까요?",
  "Set as default outbound": "기본 발신 설정으로 지정",
  "View phone numbers": "전화번호 보기",
  "Configuration not found.": "설정을 찾을 수 없습니다.",
  "Phone numbers": "전화번호",
  "Address": "주소",
  "Type": "유형",
  "Label": "라벨",
  "Inbound workflow": "수신 워크플로",
  "Delete phone number?": "전화번호를 삭제할까요?",
  "Set as default caller ID": "기본 발신자 ID로 지정",

  // Workflow editor / settings / run
  "Add node": "노드 추가",
  "Workflow settings": "워크플로 설정",
  "Zoom in": "확대",
  "Zoom out": "축소",
  "Fit view": "화면에 맞춤",
  "Tidy Up": "정리",
  "Return to the draft before starting a new test session.": "새 테스트 세션을 시작하기 전에 초안으로 돌아가세요.",
  "Save the latest draft before testing so the session uses the workflow you are looking at.": "테스트 전에 최신 초안을 저장해야 현재 보고 있는 워크플로로 세션이 시작됩니다.",
  "Resolve the current validation errors before starting another test.": "다른 테스트를 시작하기 전에 현재 검증 오류를 해결하세요.",
  "Workflow configurations not loaded": "워크플로 설정을 불러오지 못했습니다",
  "Workflow Settings": "워크플로 설정",
  "Agent Name": "에이전트 이름",
  "Enter Agent name": "에이전트 이름 입력",
  "Agent UUID": "에이전트 UUID",
  "Agent UUID copied": "에이전트 UUID가 복사되었습니다",
  "Failed to copy Agent UUID": "에이전트 UUID를 복사하지 못했습니다",
  "Ambient Noise": "배경 소음",
  "Use Ambient Noise": "배경 소음 사용",
  "Volume": "볼륨",
  "Custom Audio File": "사용자 지정 오디오 파일",
  "Turn Detection": "턴 감지",
  "Detection Strategy": "감지 전략",
  "Transcription-based": "전사 기반",
  "Smart Turn Analyzer": "스마트 턴 분석기",
  "Context Compaction": "컨텍스트 압축",
  "Call Management": "통화 관리",
  "Max Call Duration (seconds)": "최대 통화 시간(초)",
  "Unsaved changes": "저장되지 않은 변경사항",
  "Current Variables": "현재 변수",
  "Add New Variable": "새 변수 추가",
  "Key": "키",
  "Value": "값",
  "Enable Voicemail Detection": "음성사서함 감지 활성화",
  "Use Workflow LLM": "워크플로 LLM 사용",
  "System Prompt": "시스템 프롬프트",
  "Timing": "타이밍",
  "Speech Cutoff (seconds)": "음성 차단 시간(초)",
  "Model Overrides": "모델 오버라이드",
  "Template Variables": "템플릿 변수",
  "Dictionary": "사전",
  "Voicemail Detection": "음성사서함 감지",
  "Add to Website": "웹사이트에 추가",
  "Report": "리포트",
  "Duration": "통화 시간",
  "Token Usage": "토큰 사용량",
  "User Turns": "사용자 턴",
  "Bot Turns": "봇 턴",
  "Tool Calls": "도구 호출",
  "Nodes Visited": "방문한 노드",
  "Initial Context": "초기 컨텍스트",
  "Gathered Context": "수집된 컨텍스트",
  "QA Results": "QA 결과",
  "Edit your workflow to adjust the voice agent's behavior, add new steps, or modify the conversation flow.": "음성 에이전트의 동작을 조정하거나 새 단계를 추가하거나 대화 흐름을 수정하려면 워크플로를 편집하세요.",
  "Start Call": "통화 시작",
  "Start Another Test": "다른 테스트 시작",
  "Retry Call": "통화 재시도",
  "Call this agent in the browser": "브라우저에서 이 에이전트와 통화",
  "Test the agent over a voice call. Some telephony-only tools, like call transfer, are not yet supported here.": "음성 통화로 에이전트를 테스트하세요. 통화 전환 같은 일부 전화 전용 도구는 아직 여기서 지원되지 않습니다.",
  "Try Your First Web Call": "첫 웹 통화 시도",
  "Start a browser call here to hear the agent, inspect the transcript, and validate the workflow before you customize it further.": "여기서 브라우저 통화를 시작해 에이전트를 들어보고 대화 기록을 확인한 뒤 워크플로를 검증하세요.",
  "No conversation recorded": "기록된 대화가 없습니다",
  "Send a message to start the conversation.": "대화를 시작하려면 메시지를 보내세요.",
  "Send a message...": "메시지 보내기...",
  "Edit and rerun this message...": "이 메시지를 수정하고 다시 실행...",
  "Preparing chat...": "채팅 준비 중...",
  "Sending": "전송 중",
  "Send": "전송",
  "Rerunning": "다시 실행 중",
  "Rerun": "다시 실행",

  // Superadmin / run tables
  "Superadmin Dashboard": "슈퍼관리자 대시보드",
  "Manage users and view system-wide data": "사용자를 관리하고 시스템 전체 데이터를 확인하세요",
  "User Impersonation": "사용자 가장",
  "Provider User ID": "제공자 사용자 ID",
  "Workflow Runs": "워크플로 실행",
  "All Workflow Runs": "전체 워크플로 실행",
  "View and manage all workflow runs across organizations": "조직 전체의 워크플로 실행을 보고 관리하세요",
  "Workflow": "워크플로",
  "Disposition": "처리 결과",
  "Tags": "태그",
  "Details": "세부 정보",
  "Usage Info": "사용 정보",
  "Open workflow as user": "사용자로 워크플로 열기",
  "Traces": "트레이스",
  "Langfuse Traces": "Langfuse 트레이스",

  // Additional visible UI coverage
  'Local Auth Mode': '로컬 인증 모드',
  'Stack Auth handler is disabled when using local authentication.': '로컬 인증을 사용할 때는 Stack Auth 핸들러가 비활성화됩니다.',
  'This text is spoken as-is. For multilingual workflows, choose your phrasing carefully.': '이 문구는 그대로 음성으로 재생됩니다. 다국어 워크플로에서는 표현을 신중히 선택하세요.',
  'When should the AI transfer the call?': 'AI가 언제 통화를 전환해야 하나요?',
  'Please hold while I transfer your call.': '통화를 전환하는 동안 잠시만 기다려 주세요.',
  'When should the AI end the call?': 'AI가 언제 통화를 종료해야 하나요?',
  'Thank you for calling. Goodbye!': '전화해 주셔서 감사합니다. 안녕히 계세요!',
  'Book Appointment': '예약 잡기',
  'What does this tool do?': '이 도구는 무엇을 하나요?',
  'Let me check that for you, one moment please.': '확인해 보겠습니다. 잠시만 기다려 주세요.',
  'Enter provider user ID': '제공자 사용자 ID 입력',
  'Loading workflow runs...': '워크플로 실행을 불러오는 중...',
  'No service keys found': '서비스 키가 없습니다',
  'Production Server': '운영 서버',
  'Development Environment': '개발 환경',
  'Production AI Services': '운영 AI 서비스',
  'Development LLM Access': '개발 LLM 접근',
  'Default: 600 (10 minutes)': '기본값: 600(10분)',
  'Default: 10 seconds': '기본값: 10초',
  'Select strategy': '전략 선택',
  'Enter variable key': '변수 키 입력',
  'Enter variable value': '변수 값 입력',
  'Enter words separated by comma': '쉼표로 구분해 단어를 입력하세요',
  'Enter words separated by comma (e.g. billing department, tretinoin)': '쉼표로 구분해 단어를 입력하세요(예: 청구 부서, 트레티노인)',
  'Validation Errors': '검증 오류',
  'Open menu': '메뉴 열기',
  'Workflow name': '워크플로 이름',
  'Rename workflow': '워크플로 이름 변경',
  'Model Configuration': '모델 설정',
  'Words': '단어',
  'Template Context Variables': '템플릿 컨텍스트 변수',
  'Close tester panel': '테스터 패널 닫기',
  'Configurations': '설정',
  'Enable Embedding': '임베드 활성화',
  'Embed Mode': '임베드 모드',
  'Floating Widget': '플로팅 위젯',
  'Inline Component': '인라인 컴포넌트',
  'Headless (Bring Your Own UI)': '헤드리스(자체 UI 사용)',
  'Configuration': '구성',
  'Button Text': '버튼 문구',
  'Button Color': '버튼 색상',
  'Position': '위치',
  'Bottom Right': '오른쪽 아래',
  'Bottom Left': '왼쪽 아래',
  'Top Right': '오른쪽 위',
  'Top Left': '왼쪽 위',
  'Call to Action Text': '행동 유도 문구',
  'Ready to Connect': '연결 준비 완료',
  'Integration Instructions': '연동 안내',
  'Embed Code': '임베드 코드',
  'Save Configurations': '설정 저장',
  'Talk to Agent': '에이전트와 대화',
  'Click to start voice conversation': '클릭하여 음성 대화 시작',
  'Talk to Our Agent': '에이전트와 대화하기',
  'Workflow Recordings': '워크플로 녹음',
  'Add New Recordings': '새 녹음 추가',
  'Choose audio files (max 5MB each)': '오디오 파일 선택(각 최대 5MB)',
  'Rerun this turn': '이 턴 다시 실행',
  'Edit and rerun this turn': '이 턴 수정 후 다시 실행',
  'Testing is paused': '테스트가 일시 중지됨',
  'Chat with this agent': '이 에이전트와 채팅',
  'Edit the selected user message, then press Enter to rerun from that point.': '선택한 사용자 메시지를 수정한 뒤 Enter를 눌러 그 지점부터 다시 실행하세요.',
  'Describe the simulated user...': '시뮬레이션할 사용자를 설명하세요...',
  'Processed by an external service': '외부 서비스에서 처리됨',
  'How should the agent use this document?': '에이전트가 이 문서를 어떻게 사용해야 하나요?',
  'Chunked Search': '청크 검색',
  'Automation': '자동화',
  'Automate your workflows and processes': '워크플로와 프로세스를 자동화하세요',
  'Coming Soon': '준비 중',
  'Selected:': '선택됨:',
  'Telephony Configuration': '전화 설정',
  'Enable Retries': '재시도 활성화',
  'Retry Delay (seconds)': '재시도 지연(초)',
  'Busy Signal': '통화 중 신호',
  'Call Schedule': '통화 일정',
  'Timezone': '시간대',
  'Time Slots': '시간대 슬롯',
  'Circuit Breaker': '서킷 브레이커',
  'Failure Threshold (%)': '실패 임계값(%)',
  'Window (seconds)': '기간(초)',
  'Min Calls in Window': '기간 내 최소 통화 수',
  'Campaigns': '캠페인',
  'Manage your bulk workflow execution campaigns': '대량 워크플로 실행 캠페인을 관리하세요',
  'All Campaigns': '전체 캠페인',
  'Name': '이름',
  'State': '상태',
  'Progress': '진행률',
  'Created': '생성됨',
  'No campaigns found': '캠페인이 없습니다',
  'Campaign not found': '캠페인을 찾을 수 없습니다',
  'Source Type': '소스 유형',
  'Not assigned': '할당되지 않음',
  'Redial Of': '재발신 원본',
  'Redialed As': '재발신 캠페인',
  'Started At': '시작 시간',
  'Completed At': '완료 시간',
  'Using organization default': '조직 기본값 사용',
  'Activity Log': '활동 로그',
  'No events recorded yet.': '아직 기록된 이벤트가 없습니다.',
  'Redial Campaign': '캠페인 재발신',
  'Redial when last call was': '마지막 통화 상태가 다음일 때 재발신',
  'Enter voice ID': '음성 ID 입력',
  'Search voices...': '음성 검색...',
  'AI Models Configuration': 'AI 모델 설정',
  'Provider': '제공자',
  'Model': '모델',
  'API Key': 'API 키',
  'Select provider': '제공자 선택',
  'Enter API key': 'API 키 입력',
  'Something went wrong': '문제가 발생했습니다',
  'Enter model name': '모델 이름 입력',
  'Select model': '모델 선택',
  'Created At': '생성 시간',
  'Call Type': '통화 유형',
  'Inbound': '수신',
  'Outbound': '발신',
  'to': '부터',
  'e.g., Customer MCP Server': '예: 고객 MCP 서버',
  'e.g., tool_one, tool_two': '예: tool_one, tool_two',
  'e.g., Transfer Call': '예: 통화 전환',
  'e.g., End Call': '예: 통화 종료',
  'e.g., The reason for ending the call (e.g.,': '예: 통화 종료 사유(예:',
  'e.g., Book Appointment': '예: 예약 잡기',
  'e.g., greeting, hold-message': '예: greeting, hold-message',
  'example.com or *.example.com': 'example.com 또는 *.example.com',

  // Additional long-tail visible UI coverage
  'Add the embed script tag to your page (see below).': '페이지에 임베드 스크립트 태그를 추가하세요(아래 참고).',
  'The widget renders no UI — render your own buttons.': '위젯은 UI를 렌더링하지 않습니다. 자체 버튼을 렌더링하세요.',
  'Call': '호출',
  'to begin a call.': '통화를 시작합니다.',
  'to end it.': '통화를 종료합니다.',
  'Subscribe to': '구독 대상:',
  'to drive your UI.': 'UI를 제어합니다.',
  'must run inside a user-gesture handler (click) so the browser grants microphone access.': '브라우저가 마이크 접근을 허용하도록 사용자 제스처 핸들러(클릭) 안에서 실행되어야 합니다.',
  'Example — track status in your own state': '예시 — 자체 상태에서 상태 추적',
  'idle': '대기',
  'connecting': '연결 중',
  'connected': '연결됨',
  'failed': '실패',
  'Example React Component': 'React 컴포넌트 예시',
  'Add a div with id=&quot;dograh-inline-container&quot; where you want the widget': '위젯을 표시할 위치에 id=&quot;dograh-inline-container&quot; div를 추가하세요',
  'The widget will render inside this container': '위젯이 이 컨테이너 안에 렌더링됩니다',
  'You have full control over the container&apos;s styling': '컨테이너 스타일을 완전히 제어할 수 있습니다',
  'Call window.RecovaWidget.start() to begin the call': 'window.RecovaWidget.start()를 호출해 통화를 시작하세요',
  'Call window.RecovaWidget.end() to end the call': 'window.RecovaWidget.end()를 호출해 통화를 종료하세요',
  'Filter Workflow Runs': '워크플로 실행 필터',
  'Filter Templates': '필터 템플릿',
  'Active Filters': '활성 필터',
  'Select attribute to filter by': '필터링할 속성 선택',
  'Enter text': '텍스트 입력',
  'Time': '시간',
  'Select Status': '상태 선택',
  'Enter tags (comma separated)': '태그 입력(쉼표로 구분)',
  'Enter value': '값 입력',
  'Select Options': '옵션 선택',
  'Search options...': '옵션 검색...',
  'Sidebar': '사이드바',
  'Displays the mobile sidebar.': '모바일 사이드바를 표시합니다.',
  'Workflow Run History': '워크플로 실행 기록',
  'Reload': '다시 불러오기',
  'Campaign Workflow Runs': '캠페인 워크플로 실행',
  'Country (ISO-2)': '국가(ISO-2)',
  '(none)': '(없음)',
  'Default caller ID for this configuration': '이 설정의 기본 발신자 ID',
  'Configuration ID': '설정 ID',
  'Set as default for outbound calls': '발신 통화 기본값으로 설정',
  'Select a provider': '제공자 선택',
  'String': '문자열',
  'Number': '숫자',
  'Boolean': '불리언',
  'Value or Template': '값 또는 템플릿',
  'Select type': '유형 선택',
  'Describe what this parameter is for...': '이 파라미터의 용도를 설명하세요...',
  'Add Credential': '인증 정보 추가',
  'Name *': '이름 *',
  'Credential Type': '인증 정보 유형',
  'Bearer Token': 'Bearer 토큰',
  'Basic Auth': '기본 인증',
  'Custom Header': '사용자 지정 헤더',
  'My API Key': '내 API 키',
  'Optional description': '선택 설명',
  'No authentication': '인증 없음',
  'Add new credential': '새 인증 정보 추가',
  'Credential': '인증 정보',
  'Use Agent Builder': '에이전트 빌더 사용',
  'AI generates a workflow from your description': 'AI가 설명을 바탕으로 워크플로를 생성합니다',
  'Blank Canvas': '빈 캔버스',
  'Start from scratch with an empty workflow': '빈 워크플로에서 처음부터 시작합니다',
  'Total Runs': '총 실행 수',
  'Move to folder': '폴더로 이동',
  'Create folder': '폴더 생성',
  'Rename folder': '폴더 이름 변경',
  'Folder actions': '폴더 작업',
  'Folder name': '폴더 이름',
  'Reasoning Delay:': '추론 지연:',
  'Call Transcript': '통화 기록',
  'Live Transcript': '실시간 기록',
  'One more thing...': '한 가지 더...',
  'Close tooltip': '툴팁 닫기',
  'Text': '텍스트',
  'Audio': '오디오',
  'Select a recording': '녹음 선택',
  'Knowledge Base Documents': '지식 베이스 문서',
  'Add New Node': '새 노드 추가',
  'Delete node': '노드 삭제',
  'API Endpoint:': 'API 엔드포인트:',
  'Documents:': '문서:',
  'Example Request': '요청 예시',
  'Webhook URLs': '웹훅 URL',
  'Test URL': '테스트 URL',
  'Production URL': '운영 URL',
  'Click to copy URL': 'URL 복사',
  'Click to copy curl': 'curl 복사',
  'Discard changes?': '변경사항을 버릴까요?',
  'Keep Editing': '계속 편집',
  'Edit Condition': '조건 수정',
  'Condition Label': '조건 라벨',
  'Condition': '조건',
  'Transition Speech': '전환 발화',
  'Let me transfer you to our billing department...': '청구 부서로 연결해 드리겠습니다...',
  'Production Server, Development Environment': '운영 서버, 개발 환경',
  'Production AI Services, Development LLM Access': '운영 AI 서비스, 개발 LLM 접근',

  "Expires:": "만료:",
  "Keep your API keys secure. Never share them publicly or commit them to version control.": "API 키를 안전하게 보관하세요. 공개적으로 공유하거나 버전 관리에 커밋하지 마세요.",
  "Expires on:": "만료일:",
  "Automation features are currently under development": "자동화 기능은 현재 개발 중입니다",
  "We're working on powerful automation features to help you streamline your workflows.": "워크플로 운영을 간소화할 수 있는 강력한 자동화 기능을 준비하고 있습니다.",
  "Automate repetitive tasks, trigger actions based on events, and create intelligent workflow pipelines.": "반복 작업을 자동화하고, 이벤트 기반 작업을 실행하며, 지능형 워크플로 파이프라인을 만들 수 있습니다.",
  "Check back soon for updates!": "곧 업데이트 소식을 확인해 주세요!",
  "Maximum number of simultaneous calls. Leave empty to use": "동시에 진행할 수 있는 최대 통화 수입니다. 비워 두면",
  "Concurrency is limited to": "동시 통화 수는",
  "by your configured phone numbers. To use the full org limit of": "설정된 전화번호 수에 따라 제한됩니다. 조직 한도 전체를 사용하려면",
  ", add more CLIs in": ", 다음에서 CLI를 더 추가하세요:",
  "No phone numbers configured. Add CLIs in": "설정된 전화번호가 없습니다. 다음에서 CLI를 추가하세요:",
  "before running the campaign.": "캠페인을 실행하기 전입니다.",
  "Automatically retry failed calls": "실패한 통화를 자동으로 재시도",
  "Restrict when calls are made": "통화 가능 시간 제한",
  "Add Time Slot": "시간대 추가",
  "Auto-pause campaign on high failure rates": "실패율이 높으면 캠페인 자동 일시 중지",
  "Pause when failure rate exceeds this percentage": "실패율이 이 비율을 초과하면 일시 중지",
  "Upload a CSV file with contact data. Must include phone_number column.": "연락처 데이터가 포함된 CSV 파일을 업로드하세요. phone_number 열이 필요합니다.",
  "The columns can be accessed as initial_context in the workflow nodes.": "각 열은 워크플로 노드에서 initial_context로 접근할 수 있습니다.",
  "Campaign #": "캠페인 #",
  "Creates a new campaign that re-dials unique subscribers whose": "다음 조건에 해당하는 고유 구독자에게 다시 전화하는 새 캠페인을 만듭니다:",
  "last call ended with one of the selected outcomes. Subscribers": "마지막 통화가 선택한 결과 중 하나로 종료된 구독자입니다.",
  "who were successfully reached on a retry are skipped.": "재시도에서 성공적으로 연결된 구독자는 제외됩니다.",
  "View and manage your campaigns": "캠페인을 보고 관리하세요",
  "View": "보기",
  "Create your first campaign": "첫 캠페인 생성",
  "Uploaded documents are sent to Recova's managed Model Proxy Service for": "업로드한 문서는 파싱과 청킹을 위해 Recova 관리형 Model Proxy Service로 전송됩니다.",
  "parsing and chunking. Recova Model Proxy Service does not store or read your documents -": "Recova Model Proxy Service는 문서를 저장하거나 읽지 않습니다.",
  "the extracted text and embeddings are returned and stored locally in your": "추출된 텍스트와 임베딩은 반환되어 다음 위치에 로컬로 저장됩니다:",
  "self-hosted database.": "자체 호스팅 데이터베이스.",
  "The entire document is provided to the agent on each retrieval.": "검색할 때마다 전체 문서가 에이전트에 제공됩니다.",
  "Best for menus, price lists, FAQs, and other small reference documents.": "메뉴, 가격표, FAQ, 기타 작은 참고 문서에 적합합니다.",
  "The document is split into chunks and the most relevant ones are retrieved.": "문서를 청크로 나누고 가장 관련성 높은 청크를 검색합니다.",
  "Better for large documents like manuals or policies.": "매뉴얼이나 정책 같은 큰 문서에 더 적합합니다.",
  "Upload & Process": "업로드 및 처리",
  "or click to browse": "또는 클릭하여 찾아보기",
  "Supported formats:": "지원 형식:",
  "(Max 5MB)": "(최대 5MB)",
  "Choose File": "파일 선택",
  "Go Back": "뒤로 가기",
  "MB)": "MB)",
  "Impersonate a user account for debugging or support purposes": "디버깅 또는 지원 목적으로 사용자 계정을 가장합니다",
  "Access detailed information about all workflow runs, including status,": "상태를 포함한 모든 워크플로 실행의 상세 정보를 확인합니다.",
  "recordings, transcripts, and usage data.": "녹음, 대화 기록, 사용량 데이터입니다.",
  "View All Runs": "전체 실행 보기",
  "Showing": "표시 중",
  "total runs": "총 실행",
  "ID:": "ID:",
  "Page": "페이지",
  "total runs)": "총 실행)",
  "All configurations": "전체 설정",
  "Set as default": "기본값으로 지정",
  "Edit credentials": "인증 정보 수정",
  "Numbers used as caller ID for outbound and accepted for inbound matching.": "발신 통화의 발신자 ID로 사용되고 수신 매칭에 허용되는 번호입니다.",
  "Inbound docs": "수신 문서",
  "Add phone number": "전화번호 추가",
  "No phone numbers yet. Add one to start placing or receiving calls on this": "아직 전화번호가 없습니다. 이 설정에서 전화를 걸거나 받으려면 전화번호를 추가하세요.",
  "Default caller": "기본 발신자",
  "will no longer accept inbound calls or be": "더 이상 수신 전화를 받거나",
  "available as a caller ID for this configuration.": "이 설정의 발신자 ID로 사용할 수 없습니다.",
  "Connect one or more telephony provider accounts. Each campaign uses one": "하나 이상의 전화 제공자 계정을 연결하세요. 각 캠페인은 하나의",
  "configuration; inbound calls are routed to the right one by account ID.": "설정을 사용하며, 수신 전화는 계정 ID에 따라 올바른 설정으로 라우팅됩니다.",
  "Add configuration": "설정 추가",
  "missing a webhook public key. Without it, Telnyx call status": "Webhook 공개 키가 없습니다. 이 키가 없으면 Telnyx 통화 상태",
  "updates and inbound calls are being rejected. Copy your": "업데이트와 수신 전화가 거부됩니다. 다음에서",
  "public key from": "공개 키를 복사하세요:",
  "Mission Control Portal → Keys & Credentials → Public Key": "Mission Control Portal → Keys & Credentials → Public Key",
  "and paste it into the affected Telnyx configuration below.": "아래의 해당 Telnyx 설정에 붙여넣으세요.",
  "Add one to enable outbound calls and receive inbound calls.": "발신 통화와 수신 통화를 사용하려면 하나를 추가하세요.",
  "and all of its phone numbers will be removed. Any": "및 연결된 모든 전화번호가 삭제됩니다. 이 설정을 참조하는",
  "campaigns that reference this configuration will block the deletion until": "캠페인이 있으면 재할당될 때까지 삭제가 차단됩니다.",
  "they are reassigned.": "재할당될 때까지입니다.",
  "Configure the behavior when the call ends": "통화가 종료될 때의 동작을 설정합니다",
  "A descriptive name for this tool": "이 도구를 설명하는 이름",
  "Helps the LLM understand when to use this tool": "LLM이 이 도구를 언제 사용할지 이해하도록 돕습니다",
  "When enabled, the AI will provide a reason for ending the call.": "활성화하면 AI가 통화 종료 사유를 제공합니다.",
  "The reason will be set as the call disposition and added to call tags for analytics.": "이 사유는 통화 처리 결과로 설정되고 분석용 통화 태그에 추가됩니다.",
  "Instructions shown to the AI for what kind of reason to provide": "AI가 어떤 종류의 사유를 제공해야 하는지 알려주는 지침",
  "Choose whether to play a message before disconnecting": "연결을 끊기 전에 메시지를 재생할지 선택하세요",
  "End the call immediately without any message": "메시지 없이 즉시 통화를 종료합니다",
  "Play a custom message before disconnecting": "연결을 끊기 전에 사용자 지정 메시지를 재생합니다",
  "Play a pre-recorded audio file before disconnecting": "연결을 끊기 전에 사전 녹음 오디오 파일을 재생합니다",
  "Configure the HTTP API endpoint and request settings": "HTTP API 엔드포인트와 요청 설정을 구성합니다",
  "Optional message the AI will speak or play before executing this tool.": "이 도구를 실행하기 전에 AI가 말하거나 재생할 선택 메시지입니다.",
  "Define the parameters that the LLM will provide when calling this tool.": "LLM이 이 도구를 호출할 때 제공할 파라미터를 정의합니다.",
  "These will be sent as JSON body for POST/PUT/PATCH or as URL query params for GET/DELETE.": "POST/PUT/PATCH에서는 JSON 본문으로, GET/DELETE에서는 URL 쿼리 파라미터로 전송됩니다.",
  "Add values that Recova should inject at runtime. These are not exposed to the LLM and can use": "Recova가 런타임에 주입할 값을 추가하세요. 이 값은 LLM에 노출되지 않으며 다음을 사용할 수 있습니다:",
  "workflow templates like": "다음과 같은 워크플로 템플릿:",
  "or fixed literals.": "또는 고정 리터럴.",
  "Add custom headers to include in the request (optional)": "요청에 포함할 사용자 지정 헤더를 추가하세요(선택 사항)",
  "Configure call transfer settings. Supports phone numbers (Twilio) and SIP endpoints (Asterisk ARI).": "통화 전환 설정을 구성합니다. 전화번호(Twilio)와 SIP 엔드포인트(Asterisk ARI)를 지원합니다.",
  "Choose whether to play a message before transferring": "전환하기 전에 메시지를 재생할지 선택하세요",
  "Transfer the call immediately without any message": "메시지 없이 즉시 통화를 전환합니다",
  "Play a custom message before transferring": "전환하기 전에 사용자 지정 메시지를 재생합니다",
  "Play a pre-recorded audio file before transferring": "전환하기 전에 사전 녹음 오디오 파일을 재생합니다",
  "Maximum time to wait for destination to answer (5-120 seconds)": "전환 대상의 응답을 기다리는 최대 시간(5-120초)",
  "Default: 30 seconds": "기본값: 30초",
  "The name of your agent": "에이전트 이름",
  "Add background office ambient noise to make the conversation sound more natural.": "대화가 더 자연스럽게 들리도록 사무실 배경 소음을 추가합니다.",
  "Configure how the agent detects when the user has finished speaking.": "사용자가 말하기를 마쳤는지 에이전트가 감지하는 방식을 설정합니다.",
  "Incomplete Turn Timeout (seconds)": "미완료 턴 제한 시간(초)",
  "Max silence duration before ending an incomplete turn. Default: 2 seconds": "미완료 턴을 종료하기 전 최대 무음 시간입니다. 기본값: 2초",
  "Automatically summarize conversation context when transitioning between nodes. Removes stale tool calls and keeps the context clean for the new node.": "노드 간 전환 시 대화 컨텍스트를 자동으로 요약합니다. 오래된 도구 호출을 제거하고 새 노드의 컨텍스트를 깔끔하게 유지합니다.",
  "Enable Context Compaction": "컨텍스트 압축 활성화",
  "Configure call duration limits and idle timeout settings.": "통화 시간 제한과 유휴 제한 시간 설정을 구성합니다.",
  "Max User Idle Timeout (seconds)": "최대 사용자 유휴 제한 시간(초)",
  "Add any specific words that you would want the bot to actively listen for. The Voice Agent learns your": "봇이 적극적으로 인식해야 하는 특정 단어를 추가하세요. 음성 에이전트는",
  "unique words and names. Add expected words and phrases, company jargon, named entities, or industry-specific lingo.": "고유한 단어와 이름을 학습합니다. 예상 단어와 문구, 회사 용어, 고유명사, 업계 전문 용어를 추가하세요.",
  "(May incur extra cost depending on provider)": "(제공자에 따라 추가 비용이 발생할 수 있음)",
  "Save Dictionary": "사전 저장",
  "Configure Widget": "위젯 설정",
  "Add \"": "추가 \"",
  "Allow this workflow to be embedded on external websites": "이 워크플로를 외부 웹사이트에 임베드할 수 있도록 허용",
  "Allowed Domains": "허용 도메인",
  "(leave empty to allow all domains)": "(모든 도메인을 허용하려면 비워 두세요)",
  "Shows as a button in corner of the page": "페이지 모서리에 버튼으로 표시됩니다",
  "Embeds directly in your page content": "페이지 콘텐츠 안에 직접 임베드됩니다",
  "• The widget renders no UI — render your own buttons.": "• 위젯은 UI를 렌더링하지 않습니다. 자체 버튼을 렌더링하세요.",
  "• Call": "• 호출",
  "• Subscribe to": "• 구독 대상:",
  "start()": "start()",
  "Mirror the call status into a variable you control, then render whatever UI you like from it. The status values are": "통화 상태를 직접 관리하는 변수에 반영한 다음 원하는 UI를 렌더링하세요. 상태 값은 다음과 같습니다:",
  "React:": "React:",
  "• Add a div with id=\"dograh-inline-container\" where you want the widget": "• 위젯을 표시할 위치에 id=\"dograh-inline-container\" div를 추가하세요",
  "• The widget will render inside this container": "• 위젯이 이 컨테이너 안에 렌더링됩니다",
  "• You have full control over the container's styling": "• 컨테이너 스타일을 완전히 제어할 수 있습니다",
  "Copy Code": "코드 복사",
  "Configuration changes will apply automatically without re-embedding.": "설정 변경사항은 다시 임베드하지 않아도 자동으로 적용됩니다.",
  "Click": "클릭",
  "to generate your embed script.": "임베드 스크립트를 생성합니다.",
  "Override global model settings for this workflow. Toggle individual services to customize.": "이 워크플로의 전역 모델 설정을 재정의합니다. 개별 서비스를 켜서 사용자 지정하세요.",
  "Upload or record audio for hybrid prompts. Recordings are": "하이브리드 프롬프트용 오디오를 업로드하거나 녹음하세요. 녹음은",
  "scoped to your current TTS configuration. Use": "현재 TTS 설정 범위에 속합니다. 다음을 사용하세요:",
  "prompt fields to insert them.": "프롬프트 필드에 삽입합니다.",
  "Current TTS Configuration": "현재 TTS 설정",
  "VoiceID:": "VoiceID:",
  "No TTS configuration found. Set it in Model Configurations.": "TTS 설정이 없습니다. 모델 설정에서 지정하세요.",
  "Pending (": "대기 중 (",
  "No recordings yet for this TTS configuration.": "이 TTS 설정에는 아직 녹음이 없습니다.",
  "Add or remove template context variables that will be available to your workflow. You can use": "워크플로에서 사용할 수 있는 템플릿 컨텍스트 변수를 추가하거나 제거하세요. 다음을 사용할 수 있습니다:",
  "these variables within your workflow nodes within double curly braces. Example:": "워크플로 노드 안에서 이 변수를 중괄호 두 개로 감싸 사용할 수 있습니다. 예:",
  "Add Variable": "변수 추가",
  "Save Variables": "변수 저장",
  "Version History": "버전 기록",
  "No versions found.": "버전이 없습니다.",
  "Configure voicemail detection to automatically detect and end calls": "음성사서함을 자동 감지하고 통화를 종료하도록 음성사서함 감지를 설정합니다",
  "when a voicemail system is reached.": "음성사서함 시스템에 연결되었을 때입니다.",
  "Use the LLM configured in your account settings.": "계정 설정에 구성된 LLM을 사용합니다.",
  "Prompt for voicemail classification.": "음성사서함 분류용 프롬프트입니다.",
  "The LLM must respond with either \"CONVERSATION\" or \"VOICEMAIL\".": "LLM은 \"CONVERSATION\" 또는 \"VOICEMAIL\" 중 하나로 응답해야 합니다.",
  "Trigger classification early if first turn speech exceeds this duration.": "첫 턴 발화가 이 시간을 초과하면 분류를 조기에 실행합니다.",
  "Viewing": "보는 중",
  "— Read only": "- 읽기 전용",
  "Back to Draft": "초안으로 돌아가기",
  "Test Audio": "오디오 테스트",
  "Test Chat": "채팅 테스트",
  "Starting test...": "테스트 시작 중...",
  "Run Test": "테스트 실행",
  "Reset": "초기화",
  "Drive multi-turn, agent-vs-agent tests with a persona prompt.": "페르소나 프롬프트로 다중 턴 에이전트 간 테스트를 실행합니다.",
  "Coming soon": "준비 중",
  "Starting Test...": "테스트 시작 중...",
  "Start Test": "테스트 시작",
  "Download a CSV report of completed runs for this agent, optionally filtered by date range.": "이 에이전트의 완료된 실행 CSV 리포트를 다운로드합니다. 필요하면 날짜 범위로 필터링할 수 있습니다.",
  "General": "일반",
  "Agent name, call behavior, and turn detection.": "에이전트 이름, 통화 동작, 턴 감지입니다.",
  "Add background ambient noise to make the conversation sound more natural.": "대화가 더 자연스럽게 들리도록 배경 소음을 추가합니다.",
  "Upload your own audio file or use the default office ambience.": "직접 오디오 파일을 업로드하거나 기본 사무실 배경음을 사용하세요.",
  "Using default office ambience": "기본 사무실 배경음 사용 중",
  "Automatically summarize conversation context when transitioning between nodes. Not applicable in Realtime mode — the speech-to-speech service manages its own conversation state and this setting is ignored.": "노드 간 전환 시 대화 컨텍스트를 자동으로 요약합니다. 실시간 모드에는 적용되지 않습니다. 음성-음성 서비스가 자체 대화 상태를 관리하므로 이 설정은 무시됩니다.",
  "Variables available in workflow prompts via": "워크플로 프롬프트에서 사용할 수 있는 변수:",
  "syntax for testing the workflow.": "워크플로 테스트용 문법입니다.",
  "Add words the agent should actively listen for - company jargon, names,": "에이전트가 적극적으로 인식해야 하는 단어를 추가하세요. 회사 용어, 이름,",
  "industry terms. May incur extra cost depending on provider.": "업계 용어입니다. 제공자에 따라 추가 비용이 발생할 수 있습니다.",
  "Automatically detect and end calls when a voicemail system is reached.": "음성사서함 시스템에 연결되면 자동으로 감지하고 통화를 종료합니다.",
  "Stable identifier for this agent. Used in agent-stream URLs and": "이 에이전트의 안정적인 식별자입니다. agent-stream URL과",
  "other integrations where a numeric workflow ID isn't portable.": "숫자 워크플로 ID를 그대로 사용할 수 없는 기타 연동에서 사용됩니다.",
  "Copy UUID": "UUID 복사",
  "Override global model settings for this workflow. Toggle individual services to": "이 워크플로의 전역 모델 설정을 재정의합니다. 개별 서비스를 전환하여",
  "Recordings are now managed at the organization level and shared across all agents.": "녹음은 이제 조직 수준에서 관리되며 모든 에이전트가 공유합니다.",
  "in prompt fields to insert them.": "프롬프트 필드에 삽입합니다.",
  "Go to Recordings": "녹음으로 이동",
  "Configure a widget to add this voice agent to your website.": "이 음성 에이전트를 웹사이트에 추가할 위젯을 설정합니다.",
  "On this page": "이 페이지에서",
  "Privacy Policy": "개인정보처리방침",
  "Terms of Service": "서비스 이용약관",
  "Add Model Manually": "모델 수동 추가",
  "Run Preview": "미리보기 실행",
  "No recording or transcript available.": "사용 가능한 녹음 또는 대화 기록이 없습니다.",
  "Download Recording": "녹음 다운로드",
  "Download Transcript": "대화 기록 다운로드",
  "Configure your AI model, voice, and transcription services.": "AI 모델, 음성, 전사 서비스를 설정하세요.",
  "Add API Key": "API 키 추가",
  "Supported languages": "지원 언어",
  "Enter Custom Value": "사용자 지정 값 입력",
  "Override": "재정의",
  "Using global:": "전역값 사용 중:",
  "Realtime Mode": "실시간 모드",
  "Uses a single speech-to-speech model (no separate STT/TTS). An LLM is still required for variable extraction and QA.": "단일 음성-음성 모델을 사용합니다(별도 STT/TTS 없음). 변수 추출과 QA에는 여전히 LLM이 필요합니다.",
  "Add Voice ID Manually": "음성 ID 수동 추가",
  "No voices found": "음성이 없습니다",
  "voices available": "사용 가능한 음성",
  "Select All": "전체 선택",
  "Select None": "선택 해제",
  "No options found": "옵션이 없습니다",
  "Min": "최소",
  "Max": "최대",
  "View Nodes Documentation": "노드 문서 보기",
  "No documents available. Upload documents to the knowledge base first.": "사용 가능한 문서가 없습니다. 먼저 지식 베이스에 문서를 업로드하세요.",
  "Upload Documents": "문서 업로드",
  "Manage Documents": "문서 관리",
  "No recordings found. Upload recordings via the Recordings panel.": "녹음이 없습니다. 녹음 패널에서 녹음을 업로드하세요.",
  "Select a pre-recorded audio file to play.": "재생할 사전 녹음 오디오 파일을 선택하세요.",
  "No recordings match \"": "일치하는 녹음이 없습니다: \"",
  "No tools available.": "사용 가능한 도구가 없습니다.",
  "Create a Tool": "도구 생성",
  "No HTTP/native tools.": "HTTP/네이티브 도구가 없습니다.",
  "No MCP tools.": "MCP 도구가 없습니다.",
  "Refresh tools": "도구 새로고침",
  "No tools discovered — Refresh.": "발견된 도구가 없습니다 - 새로고침하세요.",
  "(unavailable)": "(사용 불가)",
  "Manage Tools": "도구 관리",
  "Enter a short label which helps identify this pathway in logs": "로그에서 이 경로를 식별하는 데 도움이 되는 짧은 라벨을 입력하세요",
  "Describe a condition that will be evaluated to determine if this pathway should be taken": "이 경로를 사용할지 판단하기 위해 평가할 조건을 설명하세요",
  "Optional text or audio the assistant will play right before transitioning to the node.": "노드로 전환하기 직전에 어시스턴트가 재생할 선택 텍스트 또는 오디오입니다.",
  "This will not be attached in Conversation Context. Use this as simple filler to reduce latency.": "이 내용은 대화 컨텍스트에 첨부되지 않습니다. 지연을 줄이는 간단한 채움 문구로 사용하세요.",
  "Test mode runs the latest draft so you can verify changes before": "테스트 모드는 최신 초안을 실행하므로 변경사항을 확인한 뒤",
  "publishing. Production runs the published agent. Both require an": "게시할 수 있습니다. 운영은 게시된 에이전트를 실행합니다. 둘 다 다음이 필요합니다:",
  "Configure the settings for this node in your workflow.": "워크플로에서 이 노드의 설정을 구성합니다.",
  "You have unsaved changes. Are you sure you want to discard them?": "저장되지 않은 변경사항이 있습니다. 정말 버리시겠습니까?",
  "Discard": "버리기",
  "Unknown property type:": "알 수 없는 속성 유형:",
  "Add": "추가",
  "Create a new credential for authentication.": "인증에 사용할 새 인증 정보를 생성합니다.",
  "No credentials found. Click the + button to create one.": "인증 정보가 없습니다. + 버튼을 클릭해 생성하세요.",
  "No parameters defined. Add a parameter to specify what data this tool needs.": "정의된 파라미터가 없습니다. 이 도구에 필요한 데이터를 지정하려면 파라미터를 추가하세요.",
  "Parameter": "파라미터",
  "Name of the parameter, like \"order_id\" or \"customer_name\"": "\"order_id\" 또는 \"customer_name\" 같은 파라미터 이름",
  "Type of the parameter, like \"string\" or \"number\" or \"boolean\"": "\"string\", \"number\", \"boolean\" 같은 파라미터 타입",
  "Description of the parameter, which makes it easy for LLM to understand, like \"The ID of the Customer to fetch Order Details\"": "LLM이 이해하기 쉽도록 하는 파라미터 설명입니다. 예: \"주문 상세를 조회할 고객 ID\"",
  "Required": "필수",
  "Add Parameter": "파라미터 추가",
  "No preset parameters defined. Add one to inject a fixed value or workflow context into the request.": "정의된 사전 설정 파라미터가 없습니다. 요청에 고정 값 또는 워크플로 컨텍스트를 주입하려면 추가하세요.",
  "Preset Parameter": "사전 설정 파라미터",
  "Key sent to the API, like \"phone_number\" or \"customer_id\"": "\"phone_number\" 또는 \"customer_id\"처럼 API로 전송되는 키",
  "Use a fixed value or a template like": "고정 값 또는 다음과 같은 템플릿을 사용하세요:",
  "Add Preset Parameter": "사전 설정 파라미터 추가",
  "Provider cannot be changed after creation.": "생성 후에는 제공업체를 변경할 수 없습니다.",
  "Used by test calls and campaigns when no specific config is selected.": "특정 설정을 선택하지 않은 테스트 통화와 캠페인에서 사용됩니다.",
  "(optional)": "(선택 사항)",
  "Phone numbers are managed separately on the configuration page.": "전화번호는 설정 페이지에서 별도로 관리됩니다.",
  "PSTN numbers (E.164), SIP URIs (sip:user@host), and SIP extensions are all supported.": "PSTN 번호(E.164), SIP URI(sip:user@host), SIP 내선을 모두 지원합니다.",
  "+19781899185, sip:101@asterisk.local, or 101": "+19781899185, sip:101@asterisk.local 또는 101",
  "Address cannot be changed. Delete this number and create a new one to": "주소는 변경할 수 없습니다. 변경하려면 이 번호를 삭제하고 새로 생성하세요:",
  "change it.": "변경하세요.",
  "Stored as": "저장 형식",
  "Used when per-number inbound routing is enabled. Today, inbound calls still": "번호별 수신 라우팅이 활성화되었을 때 사용됩니다. 현재 수신 전화는 아직",
  "route by the workflow_id in the webhook URL.": "웹훅 URL의 workflow_id 기준으로 라우팅됩니다.",
  "Used as the from-number for test calls when set.": "설정하면 테스트 통화의 발신 번호로 사용됩니다.",
  "Drag and drop your Workflow JSON File here, or Click to Select": "워크플로 JSON 파일을 여기에 끌어다 놓거나 클릭하여 선택하세요",
  "Select File": "파일 선택",
  "Arguments": "인수",
  "Result": "결과",
  "Rename": "이름 변경",
  "Delete “": "삭제 “",
  "in this folder": "이 폴더 안의",
  "won’t be deleted — they’ll move to Uncategorized.": "삭제되지 않고 미분류로 이동됩니다.",
  "Create and manage API keys for your organization": "조직의 API 키를 생성하고 관리하세요",
  "Create New Key": "새 키 생성",
  "(Full key hidden for security)": "(보안을 위해 전체 키는 숨겨짐)",
  "Last used:": "마지막 사용:",
  "Reactivate": "다시 활성화",
  "Manage service keys for accessing Recova AI services (LLM, TTS, STT)": "Recova AI 서비스(LLM, TTS, STT) 접근용 서비스 키를 관리하세요",
  "Create Service Key": "서비스 키 생성",
  "To generate additional service keys,": "추가 서비스 키를 생성하려면,",
  "Create Your First Service Key": "첫 서비스 키 생성",
  "API keys provide full access to your organization's resources.": "API 키는 조직 리소스 전체에 접근할 수 있습니다.",
  "Enter a descriptive name for your API key to help you identify it later.": "나중에 식별하기 쉽도록 API 키의 설명형 이름을 입력하세요.",
  "Create Key": "키 생성",
  "Make sure to copy your API key now. You won't be able to see it again!": "지금 API 키를 복사하세요. 다시 볼 수 없습니다!",
  "Store this key securely. It will only be shown once and cannot be retrieved later.": "이 키를 안전하게 보관하세요. 한 번만 표시되며 나중에 다시 조회할 수 없습니다.",
  "Done": "완료",
  "Create a service key to access Recova AI services (LLM, TTS, STT)": "Recova AI 서비스(LLM, TTS, STT)에 접근할 서비스 키를 생성하세요",
  "Make sure to copy your service key now. You won't be able to see it again!": "지금 서비스 키를 복사하세요. 다시 볼 수 없습니다!",
  "This key provides access to Recova AI services including LLM, Text-to-Speech, and Speech-to-Text.": "이 키는 LLM, Text-to-Speech, Speech-to-Text를 포함한 Recova AI 서비스 접근 권한을 제공합니다.",
  "Edit Campaign": "캠페인 수정",
  "Start Campaign": "캠페인 시작",
  "Pause Campaign": "캠페인 일시정지",
  "Resume Campaign": "캠페인 재개",
  "Back to Campaigns": "캠페인으로 돌아가기",
  "Clear": "지우기",
  "Configuration and source information": "설정 및 소스 정보",
  "Concurrency and retry configuration": "동시 실행 및 재시도 설정",
  "Enabled": "활성화됨",
  "Disabled": "비활성화됨",
  "Not configured": "설정되지 않음",
  "Recent state transitions and failures. Newest first.": "최근 상태 전환 및 실패 내역입니다. 최신 항목이 먼저 표시됩니다.",
  "Create Campaign": "캠페인 생성",
  "No workflow runs found.": "워크플로 실행이 없습니다.",
  "Default": "기본값",
  "Updated": "업데이트됨",
  "SIP URIs and extensions are supported alongside PSTN numbers.": "PSTN 번호와 함께 SIP URI 및 내선을 지원합니다.",
  "Provide a description which makes it easy for LLM to understand what this tool does": "LLM이 이 도구의 역할을 쉽게 이해할 수 있도록 설명을 입력하세요",
  "Use a descriptive name, like \"Get Weather using API\" for a tool that fetches weather": "날씨를 가져오는 도구라면 \"API로 날씨 조회\"처럼 설명형 이름을 사용하세요",
  "Docs": "문서",
  "Audio Files": "오디오 파일",
  "Record": "녹음",
  "Recording Name": "녹음 이름",
  "Start Recording": "녹음 시작",
  "Stop": "중지",
  "Language": "언어",
  "Try again": "다시 시도",
  "Build custom filters to find specific workflow runs": "특정 워크플로 실행을 찾기 위한 사용자 지정 필터를 만드세요",
  "Templates": "템플릿",
  "Clear All": "모두 지우기",
  "Auto-refresh every 5s": "5초마다 자동 새로고침",
  "HTTP & Tools (": "HTTP 및 도구 (",
  "MCP (": "MCP (",
  "API key in the X-API-Key header.": "X-API-Key 헤더에 API 키가 필요합니다.",
  "Get your API key": "API 키 받기",
  "JSON type to send to the API": "API로 전송할 JSON 타입",
  "Move": "이동",
  "Restore": "복원",
  "Archive": "보관",
  "Show": "표시",
  "Hide": "숨기기",
  "Created:": "생성일:",
  "Never": "없음",
  "Mon": "월",
  "Tue": "화",
  "Wed": "수",
  "Thu": "목",
  "Fri": "금",
  "Sat": "토",
  "Sun": "일",
  "Download Filtered": "필터 결과 다운로드",
  "Download All": "전체 다운로드",
  "Source File": "소스 파일",
  "Source Sheet": "소스 시트",
  "Drop your document here": "문서를 여기에 놓으세요",
  "Impersonate User": "사용자 가장",
  "Failed to copy ID": "ID 복사 실패",
  "1 Telnyx configuration is": "Telnyx 설정 1개가",
  "Phone number to transfer the call to (E.164 format with country code)": "통화를 전환할 전화번호입니다(국가 코드를 포함한 E.164 형식).",
  "PJSIP/1234 or SIP/extension@domain.com": "PJSIP/1234 또는 SIP/extension@domain.com",
  "Best for short responses (1-2 word statements). Ends turn when transcription indicates completion.": "짧은 응답(1-2단어)에 적합합니다. 전사 결과가 완료를 나타내면 턴을 종료합니다.",
  "Best for longer responses with natural pauses. Uses ML model to detect end of turn.": "자연스러운 멈춤이 있는 긴 응답에 적합합니다. ML 모델로 턴 종료를 감지합니다.",
  "Load more": "더 보기",
  "Node": "노드",
  "Edge": "엣지",
  "No value": "값 없음",
  "Custom audio": "사용자 지정 오디오",
  "Failed to play audio": "오디오 재생 실패",
  "API Key (leave empty to use global)": "API 키(전역값을 사용하려면 비워 두세요)",
  "API Key(s)": "API 키",
  "Loading voices...": "음성 불러오는 중...",
  "Apply filters": "필터 적용",
  "Read Only": "읽기 전용",
  "Click to set condition": "클릭하여 조건 설정",
  "No condition": "조건 없음",
  "No prompt configured": "설정된 프롬프트 없음",
  "Edit telephony configuration": "전화 설정 수정",
  "Add telephony configuration": "전화 설정 추가",
  "Save changes": "변경사항 저장",
  "Edit phone number": "전화번호 수정",
  "Running": "실행 중",
  "No archived agents.": "보관된 에이전트가 없습니다.",
  "No uncategorized agents.": "미분류 에이전트가 없습니다.",
  "Delete folder": "폴더 삭제",
};

const TEXT_ATTRIBUTE_NAMES = [
  "placeholder",
  "title",
  "aria-label",
  "aria-description",
  "alt",
] as const;

function shouldSkipTextNode(node: Text): boolean {
  const parent = node.parentElement;
  if (!parent) return true;
  return Boolean(parent.closest("script, style, code, pre, textarea, input, select"));
}

function translateExact(value: string): string | null {
  const trimmed = value.trim();
  if (!trimmed) return null;
  const translated = KO_DOM_TEXT_OVERRIDES[trimmed];
  if (translated) return value.replace(trimmed, translated);

  let next = value;
  for (const [source, target] of Object.entries(KO_DOM_TEXT_OVERRIDES).sort(
    ([left], [right]) => right.length - left.length,
  )) {
    if (!shouldTranslateTextFragment(source)) continue;
    next = next.split(source).join(target);
  }
  return next !== value ? next : null;
}

function shouldTranslateTextFragment(source: string): boolean {
  return (
    source.length >= 8 ||
    /[:.!?)]$/.test(source) ||
    source === "Show" ||
    source === "Hide" ||
    source === "Never"
  );
}

function translateTextNode(node: Text) {
  if (shouldSkipTextNode(node)) return;
  const next = translateExact(node.nodeValue ?? "");
  if (next && node.nodeValue !== next) {
    node.nodeValue = next;
  }
}

function translateElementAttributes(element: Element) {
  for (const attr of TEXT_ATTRIBUTE_NAMES) {
    const value = element.getAttribute(attr);
    if (!value) continue;
    const next = translateExact(value);
    if (next && next !== value) {
      element.setAttribute(attr, next);
    }
  }
}

function translateSubtree(root: ParentNode) {
  if (root instanceof Element) {
    translateElementAttributes(root);
  }

  root.querySelectorAll?.("*").forEach(translateElementAttributes);

  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  let node = walker.nextNode();
  while (node) {
    translateTextNode(node as Text);
    node = walker.nextNode();
  }
}

export function applyKoreanDomOverrides() {
  if (typeof document === "undefined") return () => {};

  const run = () => translateSubtree(document.body);
  run();

  const observer = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      if (mutation.type === "characterData") {
        translateTextNode(mutation.target as Text);
        continue;
      }
      if (mutation.type === "attributes" && mutation.target instanceof Element) {
        translateElementAttributes(mutation.target);
        continue;
      }
      mutation.addedNodes.forEach((node) => {
        if (node instanceof Text) {
          translateTextNode(node);
        } else if (node instanceof Element) {
          translateSubtree(node);
        }
      });
    }
  });

  observer.observe(document.body, {
    childList: true,
    subtree: true,
    characterData: true,
    attributes: true,
    attributeFilter: [...TEXT_ATTRIBUTE_NAMES],
  });

  return () => observer.disconnect();
}
