export const KO_DOM_TEXT_OVERRIDES: Record<string, string> = {
  // Workflow list / screenshot-critical chrome
  "Your Agents": "내 에이전트",
  "Active Agents": "활성 에이전트",
  "Upload Agent Definition": "에이전트 정의 업로드",
  "New Folder": "새 폴더",
  "Create Agent": "에이전트 생성",
  "No active workflows found. Create your first workflow to get started.": "활성 워크플로가 없습니다. 첫 워크플로를 생성해 시작하세요.",
  "Failed to load Workflows. Please Try Again Later.": "워크플로를 불러오지 못했습니다. 잠시 후 다시 시도하세요.",
  "Authentication required. Please refresh the page.": "인증이 필요합니다. 페이지를 새로고침해 주세요.",
  "Create Workflow": "워크플로 생성",
  "Upload Workflow": "워크플로 업로드",
  "Your Workflows": "내 워크플로",
  "Active Workflows": "활성 워크플로",
  "Archived": "보관됨",
  "Uncategorized": "미분류",
  "No workflows in this folder": "이 폴더에 워크플로가 없습니다",
  "No workflows found": "워크플로가 없습니다",
  "Create your first workflow": "첫 워크플로 생성",

  // Global/common controls
  "Slack 참여": "Slack 참여",
  "Star": "스타",
  "Latest": "최신",
  "Update": "업데이트",
  "Light Mode": "라이트 모드",
  "Dark Mode": "다크 모드",
  "Sign out": "로그아웃",
  "Actions": "작업",
  "Action": "작업",
  "Cancel": "취소",
  "Save": "저장",
  "Saving...": "저장 중...",
  "Create": "생성",
  "Creating...": "생성 중...",
  "Delete": "삭제",
  "Edit": "수정",
  "Refresh": "새로고침",
  "Refreshing...": "새로고침 중...",
  "Copy": "복사",
  "Copied": "복사됨",
  "Close": "닫기",
  "Back": "뒤로",
  "Next": "다음",
  "Previous": "이전",
  "Loading...": "불러오는 중...",
  "Status": "상태",
  "Active": "활성",
  "Inactive": "비활성",
  "Draft": "초안",
  "Published": "게시됨",
  "Pending": "대기 중",
  "Completed": "완료됨",
  "Failed": "실패",
  "Error": "오류",
  "Unknown": "알 수 없음",
  "None": "없음",
  "No data available": "데이터가 없습니다",
  "Learn more": "자세히 보기",
  "Click to copy": "클릭하여 복사",
  "Toggle Sidebar": "사이드바 전환",
  "Open Next.js Dev Tools": "Next.js 개발 도구 열기",
  "Notifications alt+T": "알림 alt+T",

  // Tools
  "Tools": "도구",
  "HTTP API": "HTTP API",
  "External HTTP API": "외부 HTTP API",
  "Make HTTP requests to external APIs": "외부 API로 HTTP 요청을 보냅니다",
  "End Call": "통화 종료",
  "End the call when conditions are met": "조건이 충족되면 통화를 종료합니다",
  "End the call when either user asks to disconnect the call, or when you believe its time to end the conversation": "사용자가 통화 종료를 요청했거나 대화를 끝낼 시점이라고 판단될 때 통화를 종료합니다",
  "Transfer Call": "통화 전환",
  "Transfer the call to another phone number (Twilio only)": "통화를 다른 전화번호로 전환합니다(Twilio 전용)",
  "Transfer the caller to another phone number when requested": "요청 시 발신자를 다른 전화번호로 전환합니다",
  "Calculator": "계산기",
  "Built-in calculator for arithmetic operations": "산술 계산용 기본 계산기",
  "Calculator Configuration": "계산기 설정",
  "Built-in calculator for arithmetic operations. No additional configuration needed.": "산술 계산용 기본 계산기입니다. 추가 설정이 필요 없습니다.",
  "MCP Server": "MCP 서버",
  "Native": "네이티브",
  "Native (Coming Soon)": "네이티브(준비 중)",
  "Integration": "연동",
  "Integration (Coming Soon)": "연동(준비 중)",
  "Built-in tools like call transfer, DTMF input": "통화 전환, DTMF 입력 같은 기본 도구",
  "Third-party integrations like Google Calendar": "Google Calendar 같은 외부 서비스 연동",
  "End Call Tool": "통화 종료 도구",
  "Transfer Call Tool": "통화 전환 도구",
  "HTTP API Tool": "HTTP API 도구",
  "Calculator Tool": "계산기 도구",
  "Native Tool": "네이티브 도구",
  "Integration Tool": "연동 도구",
  "MCP Server Tool": "MCP 서버 도구",
  "Tool": "도구",
  "Tool Name": "도구 이름",
  "Description": "설명",
  "Tool name": "도구 이름",
  "Describe what this tool does...": "이 도구가 하는 일을 설명하세요...",
  "Transfer Call Configuration": "통화 전환 설정",
  "Transfer Destination": "전환 대상",
  "Pre-Transfer Message": "전환 전 메시지",
  "No Message": "메시지 없음",
  "Custom Message": "사용자 지정 메시지",
  "Pre-recorded Audio": "사전 녹음 오디오",
  "Transfer Timeout": "전환 제한 시간",
  "Use phone number instead": "전화번호 사용",
  "Use SIP endpoint instead": "SIP 엔드포인트 사용",
  "End Call Configuration": "통화 종료 설정",
  "Capture End Call Reason": "통화 종료 사유 수집",
  "Reason Description": "사유 설명",
  "Goodbye Message": "종료 인사 메시지",
  "Tool Configuration": "도구 설정",
  "Settings": "설정",
  "Authentication": "인증",
  "Parameters": "파라미터",
  "HTTP Method": "HTTP 메서드",
  "Timeout (ms)": "제한 시간(ms)",
  "Endpoint URL": "엔드포인트 URL",
  "LLM Parameters": "LLM 파라미터",
  "Preset Parameters": "사전 설정 파라미터",
  "Custom Headers": "사용자 지정 헤더",
  "Header name": "헤더 이름",
  "Header value": "헤더 값",
  "Add Header": "헤더 추가",
  "Streamable HTTP": "Streamable HTTP",
  "No recordings available": "사용 가능한 녹음이 없습니다",
  "All parameters must have a name": "모든 파라미터에는 이름이 필요합니다",
  "All preset parameters must have a name and a value": "모든 사전 설정 파라미터에는 이름과 값이 필요합니다",

  // Campaigns
  "Campaign name": "캠페인 이름",
  "Enter campaign name": "캠페인 이름 입력",
  "Select a workflow": "워크플로 선택",
  "Select a telephony configuration": "전화 설정 선택",
  "Select source type": "소스 유형 선택",
  "Filter by date range": "날짜 범위로 필터링",
  "From": "시작",
  "To": "종료",
  "Start date": "시작일",
  "End date": "종료일",
  "Download Report": "리포트 다운로드",
  "Campaign Details": "캠페인 세부 정보",
  "Campaign Settings": "캠페인 설정",
  "Max Concurrent Calls": "최대 동시 통화 수",
  "Retries Enabled": "재시도 활성화",
  "Max Retries": "최대 재시도 횟수",
  "Retry Delay": "재시도 지연",
  "Retry On": "재시도 조건",
  "Busy": "통화 중",
  "No Answer": "응답 없음",
  "Voicemail": "음성사서함",
  "CSV File": "CSV 파일",
  "Upload CSV File": "CSV 파일 업로드",
  "Upload a CSV file with contact data. Must include phone_number column. The columns can be accessed as initial_context in the workflow nodes.": "연락처 데이터가 포함된 CSV 파일을 업로드하세요. phone_number 열이 필요합니다. 각 열은 워크플로 노드에서 initial_context로 접근할 수 있습니다.",
  "Max 10MB.": "최대 10MB.",

  // Files / recordings
  "Knowledge Base Files": "지식 베이스 파일",
  "Your Documents": "내 문서",
  "Upload Document": "문서 업로드",
  "Search documents...": "문서 검색...",
  "Full Document": "전체 문서",
  "Chunked": "청크 분할됨",
  "No documents uploaded yet": "아직 업로드된 문서가 없습니다",
  "No documents match your search": "검색과 일치하는 문서가 없습니다",
  "Recordings": "녹음",
  "Upload Recording": "녹음 업로드",
  "Search by ID, transcript, or filename...": "ID, 전사 또는 파일명으로 검색...",
  "Transcribing...": "전사 중...",
  "What does this recording say?": "이 녹음에서 어떤 말을 하나요?",
  "Uploading...": "업로드 중...",
  "Auto-transcription failed": "자동 전사에 실패했습니다",
  "Microphone access denied. Please allow microphone permissions.": "마이크 접근이 거부되었습니다. 마이크 권한을 허용해 주세요.",
  "Failed to upload recordings": "녹음을 업로드하지 못했습니다",
  "Failed to delete recording": "녹음을 삭제하지 못했습니다",
  "Failed to play recording": "녹음을 재생하지 못했습니다",

  // API keys / developer
  "Developer Portal": "개발자 포털",
  "Manage your API keys to access Recova services programmatically": "Recova 서비스를 프로그래밍 방식으로 사용하기 위한 API 키를 관리하세요",
  "API Keys": "API 키",
  "Create New API Key": "새 API 키 생성",
  "No API keys found": "API 키가 없습니다",
  "Create Your First API Key": "첫 API 키 생성",
  "Key Name": "키 이름",
  "API Key Created Successfully": "API 키가 생성되었습니다",
  "Your API Key:": "내 API 키:",
  "Recova Service Keys": "Recova 서비스 키",
  "Create New Service Key": "새 서비스 키 생성",
  "Service Key Name": "서비스 키 이름",
  "Service Key Created Successfully": "서비스 키가 생성되었습니다",
  "Your Service Key:": "내 서비스 키:",
  "Important:": "중요:",
  "Sign up for Recova Cloud": "Recova Cloud에 가입",

  // Telephony
  "Telephony configurations": "전화 설정",
  "Webhook public key not configured": "Webhook 공개 키가 설정되지 않았습니다",
  "No telephony configurations yet": "아직 전화 설정이 없습니다",
  "Delete configuration?": "설정을 삭제할까요?",
  "Set as default outbound": "기본 발신 설정으로 지정",
  "View phone numbers": "전화번호 보기",
  "Configuration not found.": "설정을 찾을 수 없습니다.",
  "Phone numbers": "전화번호",
  "Address": "주소",
  "Type": "유형",
  "Label": "라벨",
  "Inbound workflow": "수신 워크플로",
  "Delete phone number?": "전화번호를 삭제할까요?",
  "Set as default caller ID": "기본 발신자 ID로 지정",

  // Workflow editor / settings / run
  "Add node": "노드 추가",
  "Workflow settings": "워크플로 설정",
  "Zoom in": "확대",
  "Zoom out": "축소",
  "Fit view": "화면에 맞춤",
  "Tidy Up": "정리",
  "Return to the draft before starting a new test session.": "새 테스트 세션을 시작하기 전에 초안으로 돌아가세요.",
  "Save the latest draft before testing so the session uses the workflow you are looking at.": "테스트 전에 최신 초안을 저장해야 현재 보고 있는 워크플로로 세션이 시작됩니다.",
  "Resolve the current validation errors before starting another test.": "다른 테스트를 시작하기 전에 현재 검증 오류를 해결하세요.",
  "Workflow configurations not loaded": "워크플로 설정을 불러오지 못했습니다",
  "Workflow Settings": "워크플로 설정",
  "Agent Name": "에이전트 이름",
  "Enter Agent name": "에이전트 이름 입력",
  "Agent UUID": "에이전트 UUID",
  "Agent UUID copied": "에이전트 UUID가 복사되었습니다",
  "Failed to copy Agent UUID": "에이전트 UUID를 복사하지 못했습니다",
  "Ambient Noise": "배경 소음",
  "Use Ambient Noise": "배경 소음 사용",
  "Volume": "볼륨",
  "Custom Audio File": "사용자 지정 오디오 파일",
  "Turn Detection": "턴 감지",
  "Detection Strategy": "감지 전략",
  "Transcription-based": "전사 기반",
  "Smart Turn Analyzer": "스마트 턴 분석기",
  "Context Compaction": "컨텍스트 압축",
  "Call Management": "통화 관리",
  "Max Call Duration (seconds)": "최대 통화 시간(초)",
  "Unsaved changes": "저장되지 않은 변경사항",
  "Current Variables": "현재 변수",
  "Add New Variable": "새 변수 추가",
  "Key": "키",
  "Value": "값",
  "Enable Voicemail Detection": "음성사서함 감지 활성화",
  "Use Workflow LLM": "워크플로 LLM 사용",
  "System Prompt": "시스템 프롬프트",
  "Timing": "타이밍",
  "Speech Cutoff (seconds)": "음성 차단 시간(초)",
  "Model Overrides": "모델 오버라이드",
  "Template Variables": "템플릿 변수",
  "Dictionary": "사전",
  "Voicemail Detection": "음성사서함 감지",
  "Add to Website": "웹사이트에 추가",
  "Report": "리포트",
  "Duration": "통화 시간",
  "Token Usage": "토큰 사용량",
  "User Turns": "사용자 턴",
  "Bot Turns": "봇 턴",
  "Tool Calls": "도구 호출",
  "Nodes Visited": "방문한 노드",
  "Initial Context": "초기 컨텍스트",
  "Gathered Context": "수집된 컨텍스트",
  "QA Results": "QA 결과",
  "Edit your workflow to adjust the voice agent's behavior, add new steps, or modify the conversation flow.": "음성 에이전트의 동작을 조정하거나 새 단계를 추가하거나 대화 흐름을 수정하려면 워크플로를 편집하세요.",
  "Start Call": "통화 시작",
  "Start Another Test": "다른 테스트 시작",
  "Retry Call": "통화 재시도",
  "Call this agent in the browser": "브라우저에서 이 에이전트와 통화",
  "Test the agent over a voice call. Some telephony-only tools, like call transfer, are not yet supported here.": "음성 통화로 에이전트를 테스트하세요. 통화 전환 같은 일부 전화 전용 도구는 아직 여기서 지원되지 않습니다.",
  "Try Your First Web Call": "첫 웹 통화 시도",
  "Start a browser call here to hear the agent, inspect the transcript, and validate the workflow before you customize it further.": "여기서 브라우저 통화를 시작해 에이전트를 들어보고 대화 기록을 확인한 뒤 워크플로를 검증하세요.",
  "No conversation recorded": "기록된 대화가 없습니다",
  "Send a message to start the conversation.": "대화를 시작하려면 메시지를 보내세요.",
  "Send a message...": "메시지 보내기...",
  "Edit and rerun this message...": "이 메시지를 수정하고 다시 실행...",
  "Preparing chat...": "채팅 준비 중...",
  "Sending": "전송 중",
  "Send": "전송",
  "Rerunning": "다시 실행 중",
  "Rerun": "다시 실행",

  // Superadmin / run tables
  "Superadmin Dashboard": "슈퍼관리자 대시보드",
  "Manage users and view system-wide data": "사용자를 관리하고 시스템 전체 데이터를 확인하세요",
  "User Impersonation": "사용자 가장",
  "Provider User ID": "제공자 사용자 ID",
  "Workflow Runs": "워크플로 실행",
  "All Workflow Runs": "전체 워크플로 실행",
  "View and manage all workflow runs across organizations": "조직 전체의 워크플로 실행을 보고 관리하세요",
  "Workflow": "워크플로",
  "Disposition": "처리 결과",
  "Tags": "태그",
  "Details": "세부 정보",
  "Usage Info": "사용 정보",
  "Open workflow as user": "사용자로 워크플로 열기",
  "Traces": "트레이스",
  "Langfuse Traces": "Langfuse 트레이스",

  // Additional visible UI coverage
  'Local Auth Mode': '로컬 인증 모드',
  'Stack Auth handler is disabled when using local authentication.': '로컬 인증을 사용할 때는 Stack Auth 핸들러가 비활성화됩니다.',
  'This text is spoken as-is. For multilingual workflows, choose your phrasing carefully.': '이 문구는 그대로 음성으로 재생됩니다. 다국어 워크플로에서는 표현을 신중히 선택하세요.',
  'When should the AI transfer the call?': 'AI가 언제 통화를 전환해야 하나요?',
  'Please hold while I transfer your call.': '통화를 전환하는 동안 잠시만 기다려 주세요.',
  'When should the AI end the call?': 'AI가 언제 통화를 종료해야 하나요?',
  'Thank you for calling. Goodbye!': '전화해 주셔서 감사합니다. 안녕히 계세요!',
  'Book Appointment': '예약 잡기',
  'What does this tool do?': '이 도구는 무엇을 하나요?',
  'Let me check that for you, one moment please.': '확인해 보겠습니다. 잠시만 기다려 주세요.',
  'Enter provider user ID': '제공자 사용자 ID 입력',
  'Loading workflow runs...': '워크플로 실행을 불러오는 중...',
  'No service keys found': '서비스 키가 없습니다',
  'Production Server': '운영 서버',
  'Development Environment': '개발 환경',
  'Production AI Services': '운영 AI 서비스',
  'Development LLM Access': '개발 LLM 접근',
  'Default: 600 (10 minutes)': '기본값: 600(10분)',
  'Default: 10 seconds': '기본값: 10초',
  'Select strategy': '전략 선택',
  'Enter variable key': '변수 키 입력',
  'Enter variable value': '변수 값 입력',
  'Enter words separated by comma': '쉼표로 구분해 단어를 입력하세요',
  'Enter words separated by comma (e.g. billing department, tretinoin)': '쉼표로 구분해 단어를 입력하세요(예: 청구 부서, 트레티노인)',
  'Validation Errors': '검증 오류',
  'Open menu': '메뉴 열기',
  'Workflow name': '워크플로 이름',
  'Rename workflow': '워크플로 이름 변경',
  'Model Configuration': '모델 설정',
  'Words': '단어',
  'Template Context Variables': '템플릿 컨텍스트 변수',
  'Close tester panel': '테스터 패널 닫기',
  'Configurations': '설정',
  'Enable Embedding': '임베드 활성화',
  'Embed Mode': '임베드 모드',
  'Floating Widget': '플로팅 위젯',
  'Inline Component': '인라인 컴포넌트',
  'Headless (Bring Your Own UI)': '헤드리스(자체 UI 사용)',
  'Configuration': '구성',
  'Button Text': '버튼 문구',
  'Button Color': '버튼 색상',
  'Position': '위치',
  'Bottom Right': '오른쪽 아래',
  'Bottom Left': '왼쪽 아래',
  'Top Right': '오른쪽 위',
  'Top Left': '왼쪽 위',
  'Call to Action Text': '행동 유도 문구',
  'Ready to Connect': '연결 준비 완료',
  'Integration Instructions': '연동 안내',
  'Embed Code': '임베드 코드',
  'Save Configurations': '설정 저장',
  'Talk to Agent': '에이전트와 대화',
  'Click to start voice conversation': '클릭하여 음성 대화 시작',
  'Talk to Our Agent': '에이전트와 대화하기',
  'Workflow Recordings': '워크플로 녹음',
  'Add New Recordings': '새 녹음 추가',
  'Choose audio files (max 5MB each)': '오디오 파일 선택(각 최대 5MB)',
  'Rerun this turn': '이 턴 다시 실행',
  'Edit and rerun this turn': '이 턴 수정 후 다시 실행',
  'Testing is paused': '테스트가 일시 중지됨',
  'Chat with this agent': '이 에이전트와 채팅',
  'Edit the selected user message, then press Enter to rerun from that point.': '선택한 사용자 메시지를 수정한 뒤 Enter를 눌러 그 지점부터 다시 실행하세요.',
  'Describe the simulated user...': '시뮬레이션할 사용자를 설명하세요...',
  'Processed by an external service': '외부 서비스에서 처리됨',
  'How should the agent use this document?': '에이전트가 이 문서를 어떻게 사용해야 하나요?',
  'Chunked Search': '청크 검색',
  'Automation': '자동화',
  'Automate your workflows and processes': '워크플로와 프로세스를 자동화하세요',
  'Coming Soon': '준비 중',
  'Selected:': '선택됨:',
  'Telephony Configuration': '전화 설정',
  'Enable Retries': '재시도 활성화',
  'Retry Delay (seconds)': '재시도 지연(초)',
  'Busy Signal': '통화 중 신호',
  'Call Schedule': '통화 일정',
  'Timezone': '시간대',
  'Time Slots': '시간대 슬롯',
  'Circuit Breaker': '서킷 브레이커',
  'Failure Threshold (%)': '실패 임계값(%)',
  'Window (seconds)': '기간(초)',
  'Min Calls in Window': '기간 내 최소 통화 수',
  'Campaigns': '캠페인',
  'Manage your bulk workflow execution campaigns': '대량 워크플로 실행 캠페인을 관리하세요',
  'All Campaigns': '전체 캠페인',
  'Name': '이름',
  'State': '상태',
  'Progress': '진행률',
  'Created': '생성됨',
  'No campaigns found': '캠페인이 없습니다',
  'Campaign not found': '캠페인을 찾을 수 없습니다',
  'Source Type': '소스 유형',
  'Not assigned': '할당되지 않음',
  'Redial Of': '재발신 원본',
  'Redialed As': '재발신 캠페인',
  'Started At': '시작 시간',
  'Completed At': '완료 시간',
  'Using organization default': '조직 기본값 사용',
  'Activity Log': '활동 로그',
  'No events recorded yet.': '아직 기록된 이벤트가 없습니다.',
  'Redial Campaign': '캠페인 재발신',
  'Redial when last call was': '마지막 통화 상태가 다음일 때 재발신',
  'Enter voice ID': '음성 ID 입력',
  'Search voices...': '음성 검색...',
  'AI Models Configuration': 'AI 모델 설정',
  'Provider': '제공자',
  'Model': '모델',
  'API Key': 'API 키',
  'Select provider': '제공자 선택',
  'Enter API key': 'API 키 입력',
  'Something went wrong': '문제가 발생했습니다',
  'Enter model name': '모델 이름 입력',
  'Select model': '모델 선택',
  'Created At': '생성 시간',
  'Call Type': '통화 유형',
  'Inbound': '수신',
  'Outbound': '발신',
  'to': '부터',
  'e.g., Customer MCP Server': '예: 고객 MCP 서버',
  'e.g., tool_one, tool_two': '예: tool_one, tool_two',
  'e.g., Transfer Call': '예: 통화 전환',
  'e.g., End Call': '예: 통화 종료',
  'e.g., The reason for ending the call (e.g.,': '예: 통화 종료 사유(예:',
  'e.g., Book Appointment': '예: 예약 잡기',
  'e.g., greeting, hold-message': '예: greeting, hold-message',
  'example.com or *.example.com': 'example.com 또는 *.example.com',

  // Additional long-tail visible UI coverage
  'Add the embed script tag to your page (see below).': '페이지에 임베드 스크립트 태그를 추가하세요(아래 참고).',
  'The widget renders no UI — render your own buttons.': '위젯은 UI를 렌더링하지 않습니다. 자체 버튼을 렌더링하세요.',
  'Call': '호출',
  'to begin a call.': '통화를 시작합니다.',
  'to end it.': '통화를 종료합니다.',
  'Subscribe to': '구독 대상:',
  'to drive your UI.': 'UI를 제어합니다.',
  'must run inside a user-gesture handler (click) so the browser grants microphone access.': '브라우저가 마이크 접근을 허용하도록 사용자 제스처 핸들러(클릭) 안에서 실행되어야 합니다.',
  'Example — track status in your own state': '예시 — 자체 상태에서 상태 추적',
  'idle': '대기',
  'connecting': '연결 중',
  'connected': '연결됨',
  'failed': '실패',
  'Example React Component': 'React 컴포넌트 예시',
  'Add a div with id=&quot;dograh-inline-container&quot; where you want the widget': '위젯을 표시할 위치에 id=&quot;dograh-inline-container&quot; div를 추가하세요',
  'The widget will render inside this container': '위젯이 이 컨테이너 안에 렌더링됩니다',
  'You have full control over the container&apos;s styling': '컨테이너 스타일을 완전히 제어할 수 있습니다',
  'Call window.RecovaWidget.start() to begin the call': 'window.RecovaWidget.start()를 호출해 통화를 시작하세요',
  'Call window.RecovaWidget.end() to end the call': 'window.RecovaWidget.end()를 호출해 통화를 종료하세요',
  'Filter Workflow Runs': '워크플로 실행 필터',
  'Filter Templates': '필터 템플릿',
  'Active Filters': '활성 필터',
  'Select attribute to filter by': '필터링할 속성 선택',
  'Enter text': '텍스트 입력',
  'Time': '시간',
  'Select Status': '상태 선택',
  'Enter tags (comma separated)': '태그 입력(쉼표로 구분)',
  'Enter value': '값 입력',
  'Select Options': '옵션 선택',
  'Search options...': '옵션 검색...',
  'Sidebar': '사이드바',
  'Displays the mobile sidebar.': '모바일 사이드바를 표시합니다.',
  'Workflow Run History': '워크플로 실행 기록',
  'Reload': '다시 불러오기',
  'Campaign Workflow Runs': '캠페인 워크플로 실행',
  'Country (ISO-2)': '국가(ISO-2)',
  '(none)': '(없음)',
  'Default caller ID for this configuration': '이 설정의 기본 발신자 ID',
  'Configuration ID': '설정 ID',
  'Set as default for outbound calls': '발신 통화 기본값으로 설정',
  'Select a provider': '제공자 선택',
  'String': '문자열',
  'Number': '숫자',
  'Boolean': '불리언',
  'Value or Template': '값 또는 템플릿',
  'Select type': '유형 선택',
  'Describe what this parameter is for...': '이 파라미터의 용도를 설명하세요...',
  'Add Credential': '인증 정보 추가',
  'Name *': '이름 *',
  'Credential Type': '인증 정보 유형',
  'Bearer Token': 'Bearer 토큰',
  'Basic Auth': '기본 인증',
  'Custom Header': '사용자 지정 헤더',
  'My API Key': '내 API 키',
  'Optional description': '선택 설명',
  'No authentication': '인증 없음',
  'Add new credential': '새 인증 정보 추가',
  'Credential': '인증 정보',
  'Use Agent Builder': '에이전트 빌더 사용',
  'AI generates a workflow from your description': 'AI가 설명을 바탕으로 워크플로를 생성합니다',
  'Blank Canvas': '빈 캔버스',
  'Start from scratch with an empty workflow': '빈 워크플로에서 처음부터 시작합니다',
  'Total Runs': '총 실행 수',
  'Move to folder': '폴더로 이동',
  'Create folder': '폴더 생성',
  'Rename folder': '폴더 이름 변경',
  'Folder actions': '폴더 작업',
  'Folder name': '폴더 이름',
  'Reasoning Delay:': '추론 지연:',
  'Call Transcript': '통화 기록',
  'Live Transcript': '실시간 기록',
  'One more thing...': '한 가지 더...',
  'Close tooltip': '툴팁 닫기',
  'Text': '텍스트',
  'Audio': '오디오',
  'Select a recording': '녹음 선택',
  'Knowledge Base Documents': '지식 베이스 문서',
  'Add New Node': '새 노드 추가',
  'Delete node': '노드 삭제',
  'API Endpoint:': 'API 엔드포인트:',
  'Documents:': '문서:',
  'Example Request': '요청 예시',
  'Webhook URLs': '웹훅 URL',
  'Test URL': '테스트 URL',
  'Production URL': '운영 URL',
  'Click to copy URL': 'URL 복사',
  'Click to copy curl': 'curl 복사',
  'Discard changes?': '변경사항을 버릴까요?',
  'Keep Editing': '계속 편집',
  'Edit Condition': '조건 수정',
  'Condition Label': '조건 라벨',
  'Condition': '조건',
  'Transition Speech': '전환 발화',
  'Let me transfer you to our billing department...': '청구 부서로 연결해 드리겠습니다...',
  'Production Server, Development Environment': '운영 서버, 개발 환경',
  'Production AI Services, Development LLM Access': '운영 AI 서비스, 개발 LLM 접근',
};

const TEXT_ATTRIBUTE_NAMES = [
  "placeholder",
  "title",
  "aria-label",
  "aria-description",
  "alt",
] as const;

function shouldSkipTextNode(node: Text): boolean {
  const parent = node.parentElement;
  if (!parent) return true;
  return Boolean(parent.closest("script, style, code, pre, textarea, input, select"));
}

function translateExact(value: string): string | null {
  const trimmed = value.trim();
  if (!trimmed) return null;
  const translated = KO_DOM_TEXT_OVERRIDES[trimmed];
  if (!translated) return null;
  return value.replace(trimmed, translated);
}

function translateTextNode(node: Text) {
  if (shouldSkipTextNode(node)) return;
  const next = translateExact(node.nodeValue ?? "");
  if (next && node.nodeValue !== next) {
    node.nodeValue = next;
  }
}

function translateElementAttributes(element: Element) {
  for (const attr of TEXT_ATTRIBUTE_NAMES) {
    const value = element.getAttribute(attr);
    if (!value) continue;
    const next = translateExact(value);
    if (next && next !== value) {
      element.setAttribute(attr, next);
    }
  }
}

function translateSubtree(root: ParentNode) {
  if (root instanceof Element) {
    translateElementAttributes(root);
  }

  root.querySelectorAll?.("*").forEach(translateElementAttributes);

  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  let node = walker.nextNode();
  while (node) {
    translateTextNode(node as Text);
    node = walker.nextNode();
  }
}

export function applyKoreanDomOverrides() {
  if (typeof document === "undefined") return () => {};

  const run = () => translateSubtree(document.body);
  run();

  const observer = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      if (mutation.type === "characterData") {
        translateTextNode(mutation.target as Text);
        continue;
      }
      if (mutation.type === "attributes" && mutation.target instanceof Element) {
        translateElementAttributes(mutation.target);
        continue;
      }
      mutation.addedNodes.forEach((node) => {
        if (node instanceof Text) {
          translateTextNode(node);
        } else if (node instanceof Element) {
          translateSubtree(node);
        }
      });
    }
  });

  observer.observe(document.body, {
    childList: true,
    subtree: true,
    characterData: true,
    attributes: true,
    attributeFilter: [...TEXT_ATTRIBUTE_NAMES],
  });

  return () => observer.disconnect();
}
