"""Public API for the DB-less Recova/Jambonz facade core.

Deployment slices provide concrete F12, stock, and signature-verifier adapters to
``create_facade_app``. This package intentionally provides no ambient defaults.
"""

from .app import create_facade_app
from .auth import (
    AuthenticationError,
    SignatureVerifier,
    VerificationPolicy,
    validate_dispatch_capability,
    validate_dispatch_receipt,
    validate_media_receipt_domain,
)
from .models import (
    CONTRACT_VERSION,
    DISPATCH_VERIFICATION_DOMAIN,
    MEDIA_VERIFICATION_DOMAIN,
    AnswerAuthorityRequest,
    BoundCallContext,
    CallStatus,
    CallStatusResponse,
    CallbackReceipt,
    ContainmentRequest,
    Direction,
    DispatchConsumeReceipt,
    DispatchSubmission,
    FailureCategory,
    HookResponse,
    InboundInitialHookRequest,
    MediaAuthorityReceipt,
    NormalizedCallEvent,
    OuterCallCreateRequest,
    OuterCallCreateResponse,
    OutboundAnswerHookRequest,
    RedactedEvent,
    SignedCapability,
    StockCallBindReceipt,
    StockCallBindRequest,
    StockCallCreateRequest,
    StockCallCreateResult,
    StockCdrEvent,
    StockStatusEvent,
)
from .service import (
    AuthorityClientError,
    F12AuthorityClient,
    FacadeError,
    FacadeService,
    StockClientError,
    StockJambonzClient,
    canonical_model_digest,
    normalize_stock_cdr,
    normalize_stock_status,
    outbound_create_request_digest,
)

__all__ = [
    "CONTRACT_VERSION",
    "DISPATCH_VERIFICATION_DOMAIN",
    "MEDIA_VERIFICATION_DOMAIN",
    "AnswerAuthorityRequest",
    "AuthenticationError",
    "AuthorityClientError",
    "BoundCallContext",
    "CallStatus",
    "CallStatusResponse",
    "CallbackReceipt",
    "ContainmentRequest",
    "Direction",
    "DispatchConsumeReceipt",
    "DispatchSubmission",
    "F12AuthorityClient",
    "FacadeError",
    "FacadeService",
    "FailureCategory",
    "HookResponse",
    "InboundInitialHookRequest",
    "MediaAuthorityReceipt",
    "NormalizedCallEvent",
    "OuterCallCreateRequest",
    "OuterCallCreateResponse",
    "OutboundAnswerHookRequest",
    "RedactedEvent",
    "SignatureVerifier",
    "SignedCapability",
    "StockCallBindReceipt",
    "StockCallBindRequest",
    "StockCallCreateRequest",
    "StockCallCreateResult",
    "StockCdrEvent",
    "StockClientError",
    "StockJambonzClient",
    "StockStatusEvent",
    "VerificationPolicy",
    "canonical_model_digest",
    "normalize_stock_cdr",
    "normalize_stock_status",
    "create_facade_app",
    "outbound_create_request_digest",
    "validate_dispatch_capability",
    "validate_dispatch_receipt",
    "validate_media_receipt_domain",
]
